### ISSUE TITLE
The notification platform is unavailable

### ISSUE THREAD

**Issue by MaeiMaei** [bluskript/xsoverlay-notifier#2]
Hey, I've spun up a fresh Windows 10 Pro Education machine running 22H2 (~~19045.2006~~ bumped to 19045.2546 with same issue).
When I run the script using the one-liner, xsoverlay_notifier.exe shows the following:
```
Requesting notification access
Notification access granted
Windows notification listener died unexpectedly: Err(failed to register notification change handler

Caused by:
    The notification platform is unavailable. (0x803E0105))
Restarting listener
```
which then floods the console.

Would you know why is this the case or if you know a fix? I can understand if you're not looking to maintain this side project anymore as well.

**Comment by bluskript** [comment]
So much for MSIX bundles being reproducible lol. I actually faced this issue in development, and I'm not exactly sure why this breaks the way it does. Here's a couple of things to try:

- check that you're not on Do Not Disturb mode
- try checking if Run As Administrator fixes the issue
- try turning it off and on again

But if that doesn't work out then.. sadly there's a chance that the only fix would be to repair or maybe even fully reinstall windows.  I had to do it multiple times during development, and the first time I needed to do it was because the windows notification system was broken, and whenever my app requested to listen for notifs it would crash the whole notification system. While I was able to fix that issue without a reinstall (I forgot exactly how), I later ran into this issue which was only fixed with a full format and reinstall.
![image](https://user-images.githubusercontent.com/52386117/213845166-80b8ff59-19ed-46e9-8f26-2be3a4286182.png)

**Comment by bluskript** [comment]
It truly is frustrating how unstable this API is. I have asked multiple people to test this and it worked perfectly fine out of the box for basically everyone, but there seems to be a small percentage of people that seem to get affected by this issue, my suspicion is either an A/B test or a regression that MS hasn't caught onto at all. https://stackoverflow.com/questions/74918580/usernotificationlistener-the-remote-procedure-call-failed
![image](https://user-images.githubusercontent.com/52386117/213845265-90949e71-bf65-4e1c-9eb3-d25241da03d4.png)

**Comment by MaeiMaei** [comment]
I've checked Event Viewer and got
`
The Windows Push Notifications User Service_6a368 service terminated unexpectedly.  It has done this 2 time(s).  The following corrective action will be taken in 10000 milliseconds: Restart the service.
`
Which would check out with your record with the notification system breaking.

The problem is that I've tried on both fresh installs for Win Enterprise and Pro Edu, which I mostly always do with reformat.
This *shouldn't* be corruption issue unless either my USB or the tool to put Windows on that failed.
And even if it was, it sounds like winning the lottery if that would affect only the API multiple times.

At maximum, I could reinstall again with a consumer build and see if that fixes the problem.

**Comment by bluskript** [comment]
Yep, this is exactly what happened to me! If you would like to see it working, try it in a VM, this really made me realize that my system is just broken. I'm not sure if Win Enterprise and Pro Edu in particular have issues, but I faced this issue with a consumer build and it only got fixed with a full complete reinstall (NOTE: resetting did NOT work for me. A full reformat is necessary from what I could tell)
![image](https://user-images.githubusercontent.com/52386117/213848458-efdc3941-9bc2-47fa-bc66-71392d8a8eba.png)
![image](https://user-images.githubusercontent.com/52386117/213848484-e6dff190-abe2-4356-b516-d981e7e3875f.png)

Eventually, I could theoretically add a fallback listener system where if it fails it switches to a polling method (getting a notification list works perfectly fine even with a broken notification system, but diffing between two is unnecessarily CPU intensive and annoying so I didn't want to do it, assuming this was a rare bug that only happened to me)

**Comment by MaeiMaei** [comment]
I have done a full reinstall with reformat and it still shows the same error on Windows Home.
I've done zero customizations and I am willing to chalk this up to a regression on Microsoft's part.

**Comment by bluskript** [comment]
If you're able to reach someone at Microsoft, that'd be great. My issue on Feedback Hub doesn't seem to have gotten any attention, and I'm not sure how else to contact someone at Microsoft considering I'm not a business. Really hoping this isn't just some super weird A/B test...

**Comment by MaeiMaei** [comment]
> try it in a VM

Alright, so I have spun up a Hyper-V VM running Windows 10 Pro straight from the iso since someone bugged me to do so.
![image](https://user-images.githubusercontent.com/36708517/213895510-9a8c4ee5-9fda-433b-b4a2-0bc8bf2e428c.png)

I'm inclined to spin up a 11 VM next for shits and giggles since your screenshot does show 11.

**Comment by bluskript** [comment]
Hey @MaeiMaei try out with the latest release I just published! I added a new "polling" mode to the notification fetcher, you can configure it in `%APPDATA%\blusk\xsoverlay_notifier\config\config.toml`

This should work regardless of if you have a working listener setup as what it does is just poll notifications at a given interval (250ms by default)

**Comment by MaeiMaei** [comment]
Hey, gave it a spin, it works pretty well here and only nibbles on resources.

The only nitpicks I have is that notifications go away too fast (like half a second?), you might want to expose that to config since that sounds like a preference thing.

Also it fails to read the logo for Discord notifications.

Besides those two, looks great!

**Comment by bluskript** [comment]
Its sadly impossible to read the logo for discord notifications. the windows API for notifications is EXTREMELY limited in scope and i myself found it extremely disappointing considering I was expecting it to be more robust. I guess the API was only made in the first place expecting only smart watches to use it :/

I'll add configs options for notification speed. Thanks for giving this a test!
